# Generated by Django 4.2.19 on 2025-02-24 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("countries_plus", "0005_auto_20160224_1804"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestrictionAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=250)),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=250)),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Restriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_of_measure", models.TextField(null=True)),
                ("type_of_measure", models.TextField(null=True)),
                (
                    "restriction_type",
                    models.CharField(
                        choices=[
                            ("Quantitative", "Quantitative"),
                            ("Qualitative", "Qualitative"),
                        ],
                        default="Quantitative",
                        max_length=50,
                    ),
                ),
                (
                    "restriction_on_national_treatment",
                    models.CharField(max_length=250, null=True),
                ),
                (
                    "non_compliance",
                    models.CharField(
                        choices=[("De Jure", "De Jure"), ("De Facto", "De Facto")],
                        default="De Jure",
                        max_length=50,
                    ),
                ),
                (
                    "mode_of_supply_affected",
                    models.CharField(max_length=250, null=True),
                ),
                ("responsible_ministry", models.CharField(max_length=250)),
                ("commitments_made", models.TextField()),
                ("numerical_indicator", models.FloatField(null=True)),
                ("year_introduced", models.IntegerField(null=True)),
                ("year_of_removal_proposal", models.IntegerField(null=True)),
                ("year_of_removal", models.IntegerField(null=True)),
                ("complaints", models.TextField()),
                ("remarks", models.TextField()),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restrictions",
                        to="countries_plus.country",
                    ),
                ),
                (
                    "restriction_access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restrictions",
                        to="restrictions.restrictionaccess",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restrictions",
                        to="restrictions.sector",
                    ),
                ),
            ],
        ),
    ]
