# Generated by Django 4.2.19 on 2025-02-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restrictions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restriction",
            name="slug",
            field=models.CharField(default=None, max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name="restrictionaccess",
            name="slug",
            field=models.CharField(default=None, max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name="sector",
            name="slug",
            field=models.CharField(default=None, max_length=250, unique=True),
        ),
    ]
