# Generated by Django 4.2.19 on 2025-03-26 08:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("restrictions", "0002_restriction_slug_restrictionaccess_slug_sector_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="sectors",
                to="restrictions.sector",
            ),
        ),
        migrations.RemoveField(
            model_name="restriction",
            name="restriction_access",
        ),
        migrations.AlterField(
            model_name="restriction",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="restrictions",
                to="restrictions.sector",
            ),
        ),
        migrations.AlterField(
            model_name="restriction",
            name="slug",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="restrictionaccess",
            name="slug",
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="sector",
            name="slug",
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name="restriction",
            name="restriction_access",
            field=models.ManyToManyField(to="restrictions.restrictionaccess"),
        ),
    ]
