# Generated by Django 4.2.19 on 2025-03-26 19:06

from django.db import migrations, models
import uuid


def gen_uuid(model):
    def fn(apps, schema_editor):
        MyModel = apps.get_model("restrictions", model)
        for row in MyModel.objects.all():
            row.slug = uuid.uuid4()
            row.save(update_fields=["slug"])

    return fn


class Migration(migrations.Migration):

    dependencies = [
        (
            "restrictions",
            "0003_sector_parent_remove_restriction_restriction_access_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restriction",
            options={"ordering": ["type_of_measure"]},
        ),
        migrations.AlterModelOptions(
            name="restrictionaccess",
            options={"ordering": ["label"]},
        ),
        migrations.AlterModelOptions(
            name="sector",
            options={"ordering": ["label"]},
        ),
        migrations.RemoveField(
            model_name="sector",
            name="slug",
        ),
        migrations.AddField(
            model_name="sector",
            name="slug",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(
            gen_uuid("sector"), reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="sector",
            name="slug",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
