# Generated by Django 4.2.19 on 2025-03-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restrictions", "0004_alter_restriction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restriction",
            name="update_by_partner_state",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="restriction",
            name="complaints",
            field=models.TextField(null=True),
        ),
    ]
