# Generated by Django 4.2.19 on 2025-04-10 17:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("countries_plus", "0005_auto_20160224_1804"),
        ("restrictions", "0005_restriction_update_by_partner_state_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("date_of_occurrence", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Rejected", "Rejected"),
                            ("Review", "Review"),
                            ("Resolved", "Resolved"),
                        ],
                        default="New",
                        max_length=50,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to="countries_plus.country",
                    ),
                ),
                (
                    "restriction_access",
                    models.ManyToManyField(to="restrictions.restrictionaccess"),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="complaints",
                        to="restrictions.sector",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="restriction",
            name="restriction_type",
            field=models.CharField(
                choices=[
                    ("Quantitative", "Quantitative"),
                    ("Qualitative", "Qualitative"),
                    ("Full", "Quantitative and Qualitative"),
                ],
                default="Quantitative",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ComplaintDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="")),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="restrictions.complaint",
                    ),
                ),
            ],
        ),
    ]
