# Generated by Django 4.2.19 on 2025-04-11 09:59

import apps.bones.drf.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("countries_plus", "0005_auto_20160224_1804"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restrictions", "0006_complaint_alter_restriction_restriction_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complaint",
            options={"ordering": ["sector"]},
        ),
        migrations.AlterModelOptions(
            name="complaintdocument",
            options={"ordering": ["complaint"]},
        ),
        migrations.AddField(
            model_name="complaint",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="complaints",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restriction",
            name="type_of_measure_code",
            field=models.CharField(
                choices=[
                    ("Law", "Law"),
                    ("Decision", "Decision"),
                    ("Administrative", "Administrative Practice"),
                    ("Other", "Other"),
                ],
                default="Law",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="complaints",
                to="countries_plus.country",
            ),
        ),
        migrations.AlterField(
            model_name="complaintdocument",
            name="document",
            field=models.FileField(upload_to=apps.bones.drf.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name="restriction",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="restrictions",
                to="countries_plus.country",
            ),
        ),
    ]
