# Generated by Django 4.2.19 on 2025-04-17 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restrictions", "0007_alter_complaint_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=250, unique=True)),
                ("label", models.CharField(max_length=250)),
                ("description", models.TextField(null=True)),
            ],
            options={
                "ordering": ["label"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="restriction",
            name="commitments_made",
        ),
        migrations.RemoveField(
            model_name="restriction",
            name="complaints",
        ),
        migrations.RemoveField(
            model_name="restriction",
            name="numerical_indicator",
        ),
        migrations.AddField(
            model_name="restriction",
            name="committed_to_liberalise",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], max_length=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="restriction",
            name="mode_of_supply_affected",
            field=models.CharField(
                choices=[
                    ("Mode 1", "Mode 1: Cross-border supply"),
                    ("Mode 2", "Mode 2: Consumption abroad"),
                    ("Mode 3", "Mode 3: Establishment of a commercial presence"),
                    ("Mode 4", "Mode 4: Movement of natural persons"),
                    ("Mode 3 & 4", "Mode 3 & 4"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="restriction",
            name="remarks",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="restriction",
            name="restriction_on_national_treatment",
            field=models.CharField(
                choices=[
                    ("Fair", "Not Discriminatory"),
                    ("Discriminatory", "Discriminatory"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="restriction",
            name="policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="restrictions",
                to="restrictions.policy",
            ),
        ),
        migrations.AlterField(
            model_name="restriction",
            name="type_of_measure",
            field=models.TextField(default="None"),
            preserve_default=False,
        ),
    ]
