# Generated by Django 4.2.19 on 2025-04-18 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restrictions", "0008_policy_remove_restriction_commitments_made_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="mode_of_supply_affected",
            field=models.CharField(
                choices=[
                    ("Mode 1", "Mode 1: Cross-border supply"),
                    ("Mode 2", "Mode 2: Consumption abroad"),
                    ("Mode 3", "Mode 3: Establishment of a commercial presence"),
                    ("Mode 4", "Mode 4: Movement of natural persons"),
                    ("Mode 3 & 4", "Mode 3 & 4"),
                ],
                default=None,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="complaint",
            name="policy",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="complaints",
                to="restrictions.policy",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ComplaintLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("comments", models.TextField()),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="restrictions.complaint",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="complaintlogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["complaint"],
            },
        ),
    ]
