# Generated by Django 4.2.19 on 2025-04-24 13:44

import apps.bones.drf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restrictions",
            "0009_complaint_mode_of_supply_affected_complaint_policy_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaintdocument",
            name="document",
            field=models.FileField(
                db_column="document", upload_to=apps.bones.drf.models.get_upload_path
            ),
        ),
        migrations.RenameField(
            model_name="complaintdocument",
            old_name="document",
            new_name="_document",
        ),
    ]
