# Generated by Django 4.2.19 on 2025-04-30 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("countries_plus", "0005_auto_20160224_1804"),
        ("restrictions", "0010_alter_complaintdocument_document_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="complaint",
            name="mode_of_supply_affected",
            field=models.CharField(
                choices=[
                    ("Mode 1", "Mode 1: Cross-border trade"),
                    ("Mode 2", "Mode 2: Consumption abroad"),
                    ("Mode 3", "Mode 3: Commercial presence"),
                    ("Mode 4", "Mode 4: Presence of natural persons"),
                    ("Mode 3 & 4", "Mode 3 & 4"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="restriction",
            name="mode_of_supply_affected",
            field=models.CharField(
                choices=[
                    ("Mode 1", "Mode 1: Cross-border trade"),
                    ("Mode 2", "Mode 2: Consumption abroad"),
                    ("Mode 3", "Mode 3: Commercial presence"),
                    ("Mode 4", "Mode 4: Presence of natural persons"),
                    ("Mode 3 & 4", "Mode 3 & 4"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CommitmentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(null=True)),
                (
                    "commitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="restrictions.commitment",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="commitments",
                        to="countries_plus.country",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="commitments",
                        to="restrictions.sector",
                    ),
                ),
            ],
        ),
    ]
