# Generated by Django 4.2.19 on 2025-05-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restrictions",
            "0011_commitment_alter_complaint_mode_of_supply_affected_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="restriction",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="restriction",
            name="deleted_on",
            field=models.DateTimeField(null=True),
        ),
    ]
