# Generated by Django 4.2.19 on 2025-05-21 12:47

import apps.bones.drf.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("countries_plus", "0005_auto_20160224_1804"),
        ("restrictions", "0012_restriction_deleted_restriction_deleted_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="commitment",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="commitment",
            name="label",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicability", models.CharField(max_length=250, null=True)),
                ("requirement", models.TextField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Review", "Review"),
                            ("Active", "Active"),
                        ],
                        default="Draft",
                        max_length=50,
                    ),
                ),
                ("notification_date", models.DateField(null=True)),
                (
                    "_document",
                    models.FileField(
                        db_column="document",
                        null=True,
                        upload_to=apps.bones.drf.models.get_upload_path,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="notifications",
                        to="countries_plus.country",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="notifications",
                        to="restrictions.sector",
                    ),
                ),
            ],
            options={
                "ordering": ["sector"],
            },
        ),
    ]
