# Generated by Django 4.2.19 on 2025-05-22 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("countries_plus", "0005_auto_20160224_1804"),
        ("restrictions", "0013_commitment_description_commitment_label_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="country",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="restriction_access",
        ),
        migrations.AddField(
            model_name="complaint",
            name="date_resolved",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="origin_country",
            field=models.ForeignKey(
                default="BI",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="complaints_origin",
                to="countries_plus.country",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="complaint",
            name="restriction_type",
            field=models.CharField(
                choices=[
                    ("Access", "Restriction On Market Access"),
                    ("Treatment", "Restriction On National Treatment"),
                ],
                default="Access",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="target_country",
            field=models.ForeignKey(
                default="BI",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="complaints_target",
                to="countries_plus.country",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="complaint",
            name="date_of_occurrence",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="mode_of_supply_affected",
            field=models.CharField(
                choices=[
                    ("1", "Mode 1: Cross-border trade"),
                    ("2", "Mode 2: Consumption abroad"),
                    ("3", "Mode 3: Commercial presence"),
                    ("4", "Mode 4: Movement of natural persons"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="restriction",
            name="mode_of_supply_affected",
            field=models.CharField(
                choices=[
                    ("1", "Mode 1: Cross-border trade"),
                    ("2", "Mode 2: Consumption abroad"),
                    ("3", "Mode 3: Commercial presence"),
                    ("4", "Mode 4: Movement of natural persons"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="restriction",
            name="restriction_type",
            field=models.CharField(
                choices=[
                    ("Access", "Restriction On Market Access"),
                    ("Treatment", "Restriction On National Treatment"),
                ],
                default="Access",
                max_length=50,
            ),
        ),
    ]
