# Generated by Django 4.2.19 on 2025-05-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restrictions", "0014_remove_complaint_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="date_of_occurrence",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="date_resolved",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="mode_of_supply_affected",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="restriction_type",
            field=models.CharField(
                choices=[
                    ("Access", "Restriction On Market Access"),
                    ("Treatment", "Restriction On National Treatment"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[("Unresolved", "Unresolved"), ("Resolved", "Resolved")],
                default="Unresolved",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="restriction",
            name="restriction_type",
            field=models.CharField(
                choices=[
                    ("Quantitative", "Quantitative"),
                    ("Qualitative", "Qualitative"),
                    ("Full", "Quantitative and Qualitative"),
                ],
                default="Quantitative",
                max_length=50,
            ),
        ),
    ]
