# Generated by Django 4.2.19 on 2025-05-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restrictions", "0015_alter_complaint_date_of_occurrence_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policy",
            options={"ordering": ["sequence"]},
        ),
        migrations.AddField(
            model_name="complaint",
            name="agency",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="policy",
            name="sequence",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="restriction_type",
            field=models.CharField(
                choices=[
                    ("Access", "Restriction on Market Entry"),
                    ("Treatment", "Restriction while Operating"),
                ],
                max_length=50,
            ),
        ),
    ]
