# Generated by Django 4.2.19 on 2025-06-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restrictions", "0016_alter_policy_options_complaint_agency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restriction",
            name="restriction_on_national_treatment",
            field=models.CharField(
                choices=[
                    ("Fair", "Non-Discriminatory"),
                    ("Discriminatory", "Discriminatory"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
