# Generated by Django 4.2.19 on 2025-06-10 14:35

from django.db import migrations, models
import uuid


def gen_uuid(model):
    def fn(apps, schema_editor):
        MyModel = apps.get_model("restrictions", model)
        for row in MyModel.objects.all():
            if not row.label:
                row.label = str(uuid.uuid4())
                row.save(update_fields=["label"])

    return fn


class Migration(migrations.Migration):

    dependencies = [
        ("countries_plus", "0005_auto_20160224_1804"),
        ("restrictions", "0017_alter_restriction_restriction_on_national_treatment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commitment",
            options={"ordering": ["label"]},
        ),
        migrations.AlterModelOptions(
            name="commitmentline",
            options={"ordering": ["commitment"]},
        ),
        migrations.RunPython(
            gen_uuid("commitment"), reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="commitment",
            name="label",
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="commitmentline",
            unique_together={("commitment", "country", "sector")},
        ),
    ]
