# Generated by Django 4.2.19 on 2025-06-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restrictions", "0018_alter_commitment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complaint",
            options={
                "ordering": ["sector"],
                "permissions": [
                    ("can_review", "Can review complaint"),
                    ("can_approve", "Can approve complaint"),
                ],
            },
        ),
        migrations.AddField(
            model_name="complaintlog",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("Unresolved", "Unresolved"),
                    ("Review", "Review"),
                    ("Resolved", "Resolved"),
                    ("Rejected", "Rejected"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="complaintlog",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("Unresolved", "Unresolved"),
                    ("Review", "Review"),
                    ("Resolved", "Resolved"),
                    ("Rejected", "Rejected"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("Unresolved", "Unresolved"),
                    ("Review", "Review"),
                    ("Resolved", "Resolved"),
                    ("Rejected", "Rejected"),
                ],
                default="Unresolved",
                max_length=50,
            ),
        ),
    ]
