# Generated by Django 4.2.19 on 2025-06-17 14:38

import django.db.models.deletion
from django.db import migrations, models

import apps.bones.drf.models


def set_status():
    def fn(apps, schema_editor):
        MyModel = apps.get_model("restrictions", "complaint")
        for row in MyModel.objects.filter(status="Unresolved"):
            row.status = "New"
            row.save(update_fields=["status"])
        MyModel = apps.get_model("restrictions", "complaintlog")
        for row in MyModel.objects.filter(from_status="Unresolved"):
            row.from_status = "New"
            row.save(update_fields=["from_status"])

    return fn


class Migration(migrations.Migration):

    dependencies = [
        (
            "restrictions",
            "0019_alter_complaint_options_complaintlog_from_status_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(set_status(), reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Review", "Review"),
                    ("Status", "Update Status"),
                    ("Resolved", "Resolved"),
                    ("Rejected", "Rejected"),
                ],
                default="New",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="complaintlog",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Review", "Review"),
                    ("Status", "Update Status"),
                    ("Resolved", "Resolved"),
                    ("Rejected", "Rejected"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="complaintlog",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Review", "Review"),
                    ("Status", "Update Status"),
                    ("Resolved", "Resolved"),
                    ("Rejected", "Rejected"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ComplaintLogDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_document",
                    models.FileField(
                        db_column="document",
                        upload_to=apps.bones.drf.models.get_upload_path,
                    ),
                ),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="restrictions.complaintlog",
                    ),
                ),
            ],
            options={
                "ordering": ["log"],
            },
        ),
    ]
