# Generated by Django 4.2.19 on 2025-06-19 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def update_status():
    def fn(apps, schema_editor):
        Parent = apps.get_model("restrictions", "restriction")
        Child = apps.get_model("restrictions", "restrictionupdate")
        for row in Parent.objects.all():
            details = row.update_by_partner_state or row.remarks
            remarks = row.remarks if row.update_by_partner_state else None
            if details and "None" != details.strip():
                Child.objects.create(
                    user_id=1,
                    restriction=row,
                    details=details,
                    remarks=(remarks if "None" != remarks.strip() else None),
                )

    return fn


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restrictions", "0020_alter_complaint_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="restriction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="complaints",
                to="restrictions.restriction",
            ),
        ),
        migrations.AddField(
            model_name="restriction",
            name="status",
            field=models.CharField(
                choices=[
                    ("Intact", "Neither Removed nor Amended"),
                    ("New", "Newly Introduced"),
                    ("Major", "Major Amendment"),
                    ("Minor", "Minor Amendment"),
                    ("Removed", "Completely Removed"),
                ],
                default="Intact",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Review", "Review"),
                    ("Resolved", "Resolved"),
                    ("Rejected", "Rejected"),
                    ("Status", "Update Status"),
                ],
                default="New",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="complaintlog",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Review", "Review"),
                    ("Resolved", "Resolved"),
                    ("Rejected", "Rejected"),
                    ("Status", "Update Status"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="complaintlog",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Review", "Review"),
                    ("Resolved", "Resolved"),
                    ("Rejected", "Rejected"),
                    ("Status", "Update Status"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RestrictionUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("previous_state", models.JSONField(null=True)),
                ("details", models.TextField()),
                ("remarks", models.TextField(null=True)),
                (
                    "restriction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="restrictions.restriction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="restrictionupdates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["restriction"],
            },
        ),
        migrations.RunPython(update_status(), reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="restriction",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="restriction",
            name="update_by_partner_state",
        ),
    ]
