# Generated by Django 4.2.19 on 2025-06-20 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restrictions", "0021_remove_restriction_remarks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restrictionupdate",
            name="status",
            field=models.CharField(
                choices=[
                    ("Intact", "Neither Removed nor Amended"),
                    ("New", "Newly Introduced"),
                    ("Major", "Major Amendment"),
                    ("Minor", "Minor Amendment"),
                    ("Removed", "Completely Removed"),
                ],
                default="Intact",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="restrictionupdate",
            name="restriction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updates",
                to="restrictions.restriction",
            ),
        ),
    ]
