# Generated by Django 4.2.19 on 2025-06-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restrictions", "0022_restrictionupdate_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complaint",
            options={
                "ordering": ["sector"],
                "permissions": [
                    ("can_review", "Can review complaint"),
                    ("can_approve", "Can approve complaint (regulator)"),
                    ("can_approve_regional", "Can approve complaint (regional)"),
                    ("can_approve_council", "Can approve complaint (council)"),
                ],
            },
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Status", "Update Status"),
                    ("Review", "Review"),
                    ("Regional Review", "Regional Review"),
                    ("Council Review", "Council Review"),
                    ("Resolved", "Resolved"),
                    ("Rejected", "Rejected"),
                ],
                default="New",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="complaintlog",
            name="from_status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Status", "Update Status"),
                    ("Review", "Review"),
                    ("Regional Review", "Regional Review"),
                    ("Council Review", "Council Review"),
                    ("Resolved", "Resolved"),
                    ("Rejected", "Rejected"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="complaintlog",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Status", "Update Status"),
                    ("Review", "Review"),
                    ("Regional Review", "Regional Review"),
                    ("Council Review", "Council Review"),
                    ("Resolved", "Resolved"),
                    ("Rejected", "Rejected"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
