# Generated by Django 4.2.19 on 2025-06-26 19:20

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "restrictions",
            "0023_alter_complaint_options_alter_complaint_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("applicability", "requirement"),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("label", "description"),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
        migrations.AddField(
            model_name="restriction",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("text_of_measure", "type_of_measure"),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
        migrations.AddField(
            model_name="restrictionaccess",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("label", "description"),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
        migrations.AddField(
            model_name="restrictionupdate",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("details", "remarks"),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("label", "description"),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
    ]
