# Generated by Django 4.2.19 on 2025-02-24 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_uri", models.TextField()),
                ("referrer", models.TextField()),
                ("violated_directive", models.CharField(max_length=500)),
                ("effective_directive", models.CharField(max_length=500)),
                ("original_policy", models.TextField()),
                ("blocked_uri", models.TextField()),
                ("line_number", models.SmallIntegerField(null=True)),
                ("column_number", models.SmallIntegerField(null=True)),
                ("source_file", models.TextField(null=True)),
                ("status_code", models.SmallIntegerField(null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("locale", models.CharField(default="en", max_length=250)),
                (
                    "time_zone",
                    models.CharField(default="Africa/Nairobi", max_length=250),
                ),
                ("avatar", models.ImageField(blank=True, upload_to="avatars/")),
            ],
        ),
    ]
