# Generated by Django 4.2.19 on 2025-04-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=250, unique=True)),
            ],
            options={
                "ordering": ["label"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_index", models.IntegerField()),
                (
                    "display_type",
                    models.CharField(
                        choices=[("Question", "Question"), ("Dashboard", "Dashboard")],
                        max_length=50,
                    ),
                ),
                ("label", models.CharField(max_length=250, unique=True)),
                ("brief", models.CharField(max_length=250)),
                ("description", models.TextField(null=True)),
                ("tags", models.ManyToManyField(to="core.reporttag")),
            ],
            options={
                "ordering": ["label"],
            },
        ),
    ]
