# Generated by Django 4.2.19 on 2025-04-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_reporttag_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="feature",
            field=models.BooleanField(null=True),
        ),
    ]
