# Generated by Django 4.2.19 on 2025-05-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_report_feature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="time_zone",
        ),
        migrations.AddField(
            model_name="profile",
            name="dark_mode",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
