# Generated by Django 4.2.19 on 2025-05-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_profile_time_zone_profile_dark_mode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="feature",
        ),
        migrations.AddField(
            model_name="report",
            name="sequence",
            field=models.IntegerField(null=True),
        ),
    ]
