# Generated by Django 4.2.19 on 2025-05-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_report_feature_report_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="params",
            field=models.JSONField(null=True),
        ),
    ]
