# Generated by Django 4.2.19 on 2025-05-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_report_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="activation_code",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
