# Generated by Django 4.2.19 on 2025-06-04 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("countries_plus", "0005_auto_20160224_1804"),
        ("core", "0007_profile_activation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="profiles",
                to="countries_plus.country",
            ),
        ),
    ]
