# Generated by Django 4.2.19 on 2025-06-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_profile_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="display_height",
            field=models.IntegerField(default=550, null=True),
        ),
    ]
