# Generated by Django 4.2.19 on 2025-06-26 19:24

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_report_display_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("label", "brief", "description"),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
    ]
