# Generated by Django 4.2.19 on 2025-07-02 13:00
import re

import modeltrans.fields
from django.db import migrations, models


def gen_uuid():
    def fn(apps, schema_editor):
        MyModel = apps.get_model("core", "reporttag")
        for row in MyModel.objects.all():
            s = row.label.lower()
            row.slug = "-".join([w for w in re.sub("[^\w\s]", "", s).split() if w])
            row.save(update_fields=["slug"])

    return fn


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_report_i18n"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporttag",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("label",), required_languages=(), virtual_fields=True
            ),
        ),
        migrations.AddField(
            model_name="reporttag",
            name="slug",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.RunPython(gen_uuid(), reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="reporttag",
            name="label",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="reporttag",
            name="slug",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
