# Generated by Django 4.2.23 on 2025-08-05 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_reporttag_i18n_reporttag_slug_alter_reporttag_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the page', unique=True)),
                ('title', models.CharField(help_text='Page title', max_length=255)),
                ('body', models.TextField(help_text='Page content')),
                ('published', models.BooleanField(default=False, help_text='Whether the page is publicly visible')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO meta keywords (comma-separated)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='When the page was first published', null=True)),
                ('author', models.ForeignKey(blank=True, help_text='User who created this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_cms_pages', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='User who last modified this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_cms_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('publish_cmspage', 'Can publish/unpublish CMS pages'), ('manage_all_cmspages', 'Can manage all CMS pages regardless of author')],
            },
        ),
    ]
