"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import environ

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Load the environment variables if .env file is present
if (BASE_DIR / ".env").is_file():
    environ.Env.read_env(BASE_DIR / ".env")


################################################################################
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
################################################################################

# Application definition

INSTALLED_APPS = [
    # Core Django applications
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Custom apps
    "apps.restrictions",
    "apps.core",
    "apps.spa",
    # Additional Items
    "modeltrans",
    "countries_plus",
    "corsheaders",
    "drf_yasg",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.core.middleware.CSPMiddleware",
    "apps.core.middleware.LocaleMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "static" / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
# from django.conf.global_settings import LANGUAGES, LOCALE_PATHS

LOCALE_PATHS = [
    BASE_DIR / "static" / "locale",
]
LANGUAGES = [
    ("en", "English"),
    ("fr", "French"),
]
LANGUAGE_CODE = "en"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static" / "cache"
STATICFILES_DIRS = [BASE_DIR / "static" / "static"]
STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
)

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "static" / "media"


# Caching
# https://docs.djangoproject.com/en/4.2/topics/cache/#setting-up-the-cache
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2",
    }
}


# drf settings
REST_FRAMEWORK = {
    # https://www.django-rest-framework.org/api-guide/throttling/
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {"anon": "10/day", "user": "5/minute"},
}


# drf_yasg settings
SWAGGER_SETTINGS = {
    "DEFAULT_MODEL_RENDERING": "example",
    "SECURITY_DEFINITIONS": {
        "Bearer": {"type": "apiKey", "name": "Authorization", "in": "header"}
    },
}


# Error Logging
# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "formatters": {
#         "large": {
#             "format": '\n%(asctime)s  %(levelname)s\n File "%(pathname)s" Line %(lineno)d in %(funcName)s\n\n%(message)s\n'
#         },
#         "tiny": {"format": "\n%(asctime)s  %(message)s\n"},
#     },
#     "handlers": {
#         "errors_file": {
#             "level": "ERROR",
#             "class": "logging.handlers.RotatingFileHandler",
#             "maxBytes": 10**6,
#             "backupCount": 5,
#             "filename": BASE_DIR / "logs" / "error.log",
#             "formatter": "large",
#         },
#     },
#     "loggers": {
#         "django": {
#             "handlers": ["errors_file"],
#             "level": "ERROR",
#             "propagate": False,
#         },
#     },
# }


################################################################################
# Some production settings
################################################################################

# Prevent the browser from identifying content types incorrectly.
SECURE_CONTENT_TYPE_NOSNIFF = True

# Activate the browser's XSS filtering and help prevent XSS attacks.
SECURE_BROWSER_XSS_FILTER = True

# Ensure that client-side JavaScript will not to be able to access the CSRF
# and language cookies.
LANGUAGE_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# No use of iframes in the site content
X_FRAME_OPTIONS = "DENY"

# The default csrf view to use
CSRF_FAILURE_VIEW = "apps.core.views.error_403"
